### ISSUE TITLE
[fatal] Error: Cannot find module 'hapi-auth-cookie'

### ISSUE THREAD

**Issue by YDHui** [elasticfence/kibana-auth-elasticfence#7]
I install elasticfence to my elasticsearch 5.1.2 and it work fine ,but when I install the kibana-auth-elasticfence to my kibana 5.1.2 , it can't start and return this error:

> [fatal] Error: Cannot find module 'hapi-auth-cookie'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/data/soft/kibana-5.1.2-linux-x86_64/plugins/kibana-auth-plugin/server/auth-local-cookie.js:115:21)
    at ScopedPlugin.init [as externalInit] (/data/soft/kibana-5.1.2-linux-x86_64/plugins/kibana-auth-plugin/index.js:17:44)
    at ScopedPlugin.tryCatcher (/data/soft/kibana-5.1.2-linux-x86_64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/data/soft/kibana-5.1.2-linux-x86_64/node_modules/bluebird/js/main/method.js:30:24)
    at /data/soft/kibana-5.1.2-linux-x86_64/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/data/soft/kibana-5.1.2-linux-x86_64/src/server/plugins/plugin.js:11:273)

Please reply me ,thanks

**Comment by lmangani** [comment]
Try to install it manually inside the plugin folder ```npm install hapi-auth-cookie``` or globally ```npm install -g hapi-auth-cookie```
